### PR TITLE
feature: add predictWin

### LINKED ISSUE #213: Draw probability function
Hey,
I recently released a Lua port of the OpenSkill package: https://github.com/Vaschex/openskill.lua

I wanted to ask if you know how to implement a draw probability function for n-teams, n-players. This would be very helpful to determine good team compositions.
I know that TrueSkill has such a quality function, but they are using matrices and I don't know how to port that: https://github.com/scttcper/ts-trueskill/blob/master/src/trueskill.ts

### PR DESCRIPTION
**Pull request by philihp**
See #213, and adds a new function `predictWin([team, team, ...], options)`, which returns an array of floats, which are the odds of each team winning.

### CODE REVIEW

**Comment by daegontaven** [comment]
@philihp i have a minimal working code for predicting wins, haven't tested it a lot, but i think it works

https://github.com/OpenDebates/openskill.py/pull/27

**Comment by philihp** [comment]
> @philihp i have a minimal working code for predicting wins, haven't tested it a lot, but i think it works
> 
> [OpenDebates/openskill.py#27](https://github.com/OpenDebates/openskill.py/pull/27)

Thanks for that!! Sorry been a little occupied with other things. If someone reading this feels inclined to PR, I'd love to accept it — otherwise I'll get to this next thing.

**Comment by daegontaven** [comment]
Wrote a `predict_draw` function for openskill.py. Code is here https://github.com/OpenDebates/openskill.py/pull/45. Should be easy enough to port.

Note: I am not using `quality` as the function name for two reasons:
 1. Match quality is not as explicit a function name as predict_draw
 2. Didn't want people to think we are using math from trueskill library (we are not ofc...they are using a covariance matrix).

**Comment by philihp** [comment]
Sounds reasonable. I do wish there were a good single word for it, but I agree that `predict_draw` and `predict_win` are more intuitive.

**Pull request merged**
