### PR TITLE
fix: predictDraw should give same result as python

### PR DESCRIPTION
**Pull request by philihp**
I think maybe #611 didn't exactly get us there. This creates some tests pulled from https://github.com/philihp/openskill.js/issues/599 and from https://openskill.me, and the Javascript library should give the same result.

### CODE REVIEW

**Comment by vivekjoshy** [comment]
@philihp lots of things have changed since v5.1.1 btw, for instance, predictDraw no longer ranges between 0 and 1, but between 0 and 0.5 to make it obvious that the variance is taken into account. Weights is also implemented now for rate. I was going to make an issue on this repo, but might as well comment here now.

**Comment by philihp** [comment]
Thanks! Yeah I was looking at the Python code and it looks like a lot has changed.

**Comment by philihp** [comment]
I'm seeing that you have predict functions attached to the model. Do you anticipate they'll be different?

**Comment by vivekjoshy** [comment]
No, that was done when I was considering adding other models. It actually does not make sense anymore. I will have to get around to changing it back to the way it was before, but for now it's easier to test things this way.

**Pull request merged**
